/*
* generated by Xtext
*/
package es.usj.raspduino;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RaspduinoDSLStandaloneSetup extends RaspduinoDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new RaspduinoDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

