/*
 * generated by Xtext
 */
package es.usj.raspduino;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RaspduinoDSLRuntimeModule extends es.usj.raspduino.AbstractRaspduinoDSLRuntimeModule {

}
