/*
* generated by Xtext
*/
package es.usj.raspduino.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import es.usj.raspduino.services.RaspduinoDSLGrammarAccess;

public class RaspduinoDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private RaspduinoDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected es.usj.raspduino.ui.contentassist.antlr.internal.InternalRaspduinoDSLParser createParser() {
		es.usj.raspduino.ui.contentassist.antlr.internal.InternalRaspduinoDSLParser result = new es.usj.raspduino.ui.contentassist.antlr.internal.InternalRaspduinoDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getHardwareAlternatives_3_0(), "rule__Model__HardwareAlternatives_3_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getHardwareAssignment_3(), "rule__Model__HardwareAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			es.usj.raspduino.ui.contentassist.antlr.internal.InternalRaspduinoDSLParser typedParser = (es.usj.raspduino.ui.contentassist.antlr.internal.InternalRaspduinoDSLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RaspduinoDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RaspduinoDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
