/*
 * generated by Xtext
 */
package es.usj.raspduino.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRaspduinoDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(es.usj.raspduino.raspduinoDSL.RaspduinoDSLPackage.eINSTANCE);
		return result;
	}
}
