/*
* generated by Xtext
*/
package es.usj.raspduino;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RaspduinoDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return es.usj.raspduino.ui.internal.RaspduinoDSLActivator.getInstance().getInjector("es.usj.raspduino.RaspduinoDSL");
	}
	
}
