/*
* generated by Xtext
*/
package es.usj.raspduino.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RaspduinoDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("es/usj/raspduino/parser/antlr/internal/InternalRaspduinoDSL.tokens");
	}
}
