/*
 * generated by Xtext
 */
package es.usj.raspduino.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RaspduinoDSLUiModule extends es.usj.raspduino.ui.AbstractRaspduinoDSLUiModule {
	public RaspduinoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
