/*
 * generated by Xtext
 */
package es.usj.raspduino.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import es.usj.raspduino.ui.internal.RaspduinoDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RaspduinoDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RaspduinoDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RaspduinoDSLActivator.getInstance().getInjector(RaspduinoDSLActivator.ES_USJ_RASPDUINO_RASPDUINODSL);
	}
	
}
