/*
 * generated by Xtext
 */
package es.usj.raspduino.ui.contentassist

import es.usj.raspduino.ui.contentassist.AbstractRaspduinoDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RaspduinoDSLProposalProvider extends AbstractRaspduinoDSLProposalProvider {
}
