/**
 * generated by Xtext
 */
package es.usj.raspduino.validation;

import es.usj.raspduino.validation.AbstractRaspduinoDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RaspduinoDSLValidator extends AbstractRaspduinoDSLValidator {
}
